name: Validate Pull Request

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Validate PR Description or Comments
        id: validate
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ISSUE_REF_REGEX='Fixes #[0-9]+'
          PR_COMMENTS=$(gh pr view "$GITHUB_REF" --json comments --jq '.comments[].body')
          PR_BODY=$(jq -r '.pull_request.body' "$GITHUB_EVENT_PATH")

          if ! echo "$PR_BODY" | grep -q "$ISSUE_REF_REGEX" && ! echo "$PR_COMMENTS" | grep -q "$ISSUE_REF_REGEX"; then
            echo "Error: Pull request must include a reference to an issue (e.g., 'Fixes #123') either in the description or in the comments."
            exit 1
          fi

      - name: Set status to request changes if validation fails
        if: failure()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr review --request-changes --body "Pull request description or comments must include a reference to an issue (e.g., 'Fixes #123')."
